name: "Preddies"
description: "Private Premier League prediction game"
version: "1.22.10"
slug: "premier_league_predictor"
init: false
arch:
  - amd64
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Preddies"
map:
  - data:rw
options: {}
schema: {}
panel_icon: mdi:soccer
panel_title: Preddies
